##############################################
############ Path configuration ##############
##############################################

platform:
    SRorPE: 'PE' # change to SR if used with single read data
    prefix: ['_1', '_2']
    # file name pattern, appended before .fastq.gz (*prefix.fastq.gz)
                                   # for paired end, two prefix need to be used

path:
    fastq: ['/home/shared/inbre-group1/Bioinformatics-NEURO/data']
    trimmed: '/home/shared/inbre-group1/Bioinformatics-NEURO/results/intermediate_results/trimmomatic/'
    log: '/home/shared/inbre-group1/Bioinformatics-NEURO/results/logs/'
    qc: '/home/shared/inbre-group1/Bioinformatics-NEURO/results/intermediate_results/fastqc/'
    bam: '/home/shared/inbre-group1/Bioinformatics-NEURO/results/intermediate_results/alignment/'
    htseq_counts: '/home/shared/inbre-group1/Bioinformatics-NEURO/results/intermediate_results/htseq/'
    out: '/home/shared/inbre-group1/Bioinformatics-NEURO/results/final_results/'

##############################################
############ Software options ################
##############################################

ftcount:
    threads: 20
    option: '' #for more options check the manual, e.g., for paired-end add -p option

trim:
    params:
        trimmer: ["ILLUMINACLIP:/home/shared/inbre-group1/Bioinformatics-NEURO/pipeline/Trimmomatic/TruSeq3-PE.fa:2:30:10"] # Cut bases off the end of a read, if below a threshold quality; use LEADING for begining
    threads: 10
    #For more options check the manual @ http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf

hisat2:
    threads: 16
    index: '/home/shared/inbre-group1/Bioinformatics-NEURO/pipeline/grch38/genome'
    gtf: '/home/shared/inbre-group1/Bioinformatics-NEURO/pipeline/new_genome/CHM13.v2.0.gtf'

bam:
    params: '-b -h -q20'
    #-b Output in the BAM format.
    #-h Include the header in the output.
    #-qINT Skip alignments with MAPQ smaller than INT [0]
    #For more options check the manual @ http://www.htslib.org/doc/samtools.html
htseq:
    gtf: '/home/shared/inbre-group1/Bioinformatics-NEURO/pipeline/grch38/Homo_sapiens.GRCh38.90.chr.gtf'
ftc:
    threads: 8
