##############################################
############ Path configuration ##############
##############################################

platform:
    SEorPE: 'PE' # change to SE if used with single end data
    prefix: ['_R1_001', '_R2_001'] # file name pattern, appended before .fastq.gz (*prefix.fastq.gz)
                                   # for paired end, two prefix need to be used

path:
    fastq: ['../../../archive/MPS-396-190306/190515_K00360_0524_AH5J5JBBXY/Unaligned_190516_Path/Path-MPS-396-190306-L0673']
    log: 'log/'
    qc: 'data/RNA_seq/qc/'
    bam: 'data/RNA_seq/bams/'
    out: 'data/RNA_seq/output/'

##############################################
############ Software options ################
##############################################
index:
    threads: 20 # set the maximum number of available core

ftcount:
    threads: 20
    option: '' #for more options check the manual, e.g., for paired-end add -p option

trim:
    params:
        trimmer: ["ILLUMINACLIP:/home/y.kim1/Resource/trimmomatic/adapters/TruSeq3-PE.fa:2:30:10"] # Cut bases off the end of a read, if below a threshold quality; use LEADING for begining
    threads: 10 
    #For more options check the manual @ http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf

star:
    threads: 15
    index: '/home/y.kim1/Resource/STAR_index/'
    fasta: 'STARindex/fasta/'
    gtf: '/home/y.kim1/Resource/gtf/Homo_sapiens.GRCh37.75.gtf'

bam:
    params: '-b -h -q20' 
    #-b Output in the BAM format.
    #-h Include the header in the output.
    #-qINT Skip alignments with MAPQ smaller than INT [0]
    #For more options check the manual @ http://www.htslib.org/doc/samtools.html
